# Generated by Django 5.2.3 on 2025-06-23 23:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('size', models.CharField(max_length=50)),
                ('breed', models.CharField(max_length=50)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('health_status', models.CharField(max_length=100)),
                ('vaccinated', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('available', 'Available'), ('reserved', 'Reserved'), ('adopted', 'Adopted')], default='available', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Adopter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('national_id', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('adoption_history', models.ManyToManyField(blank=True, to='app.dog')),
            ],
        ),
        migrations.CreateModel(
            name='Preferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_breed', models.CharField(blank=True, max_length=50)),
                ('preferred_size', models.CharField(blank=True, max_length=50)),
                ('accepts_unvaccinated', models.BooleanField(default=False)),
                ('adopter', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to='app.adopter')),
            ],
        ),
    ]
