# Generated by Django 5.2.3 on 2025-06-24 23:54

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adoptante',
            fields=[
                ('dni', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre_completo', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('gusta_raza', models.CharField(blank=True, choices=[('CCH', 'Caniche'), ('CH', 'Chihuahua'), ('DA', 'Dogo Argentino'), ('PIT', 'Pitbull'), ('MIX', 'Mestizo')], max_length=4, null=True)),
                ('gusta_tamaño', models.CharField(blank=True, choices=[('XS', 'Muy pequeño'), ('S', 'Pequeño'), ('M', 'Mediano'), ('L', 'Grande'), ('XL', 'Extra grande')], max_length=2, null=True)),
                ('gusta_temperamento', models.CharField(blank=True, choices=[('CAL', 'Calmo'), ('ACT', 'Activo'), ('JUG', 'Juguetón'), ('PROT', 'Protector')], max_length=4, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('codigo', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=80)),
                ('raza', models.CharField(choices=[('CCH', 'Caniche'), ('CH', 'Chihuahua'), ('DA', 'Dogo Argentino'), ('PIT', 'Pitbull'), ('MIX', 'Mestizo')], max_length=4)),
                ('edad', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(30)])),
                ('tamaño', models.CharField(choices=[('XS', 'Muy pequeño'), ('S', 'Pequeño'), ('M', 'Mediano'), ('L', 'Grande'), ('XL', 'Extra grande')], max_length=2)),
                ('peso_kg', models.DecimalField(decimal_places=2, max_digits=5)),
                ('estado_salud', models.CharField(choices=[('OK', 'Saludable'), ('OP', 'Operado'), ('TR', 'En tratamiento')], max_length=3)),
                ('esta_vacunado', models.BooleanField(default=False)),
                ('estado_actual', models.CharField(choices=[('D', 'Disponible'), ('R', 'Reservado'), ('A', 'Adoptado')], default='D', max_length=1)),
                ('temperamento', models.CharField(choices=[('CAL', 'Calmo'), ('ACT', 'Activo'), ('JUG', 'Juguetón'), ('PROT', 'Protector')], max_length=4)),
            ],
        ),
        migrations.RemoveField(
            model_name='adopter',
            name='adoption_history',
        ),
        migrations.RemoveField(
            model_name='preferences',
            name='adopter',
        ),
        migrations.CreateModel(
            name='RegistroAdopcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_adopcion', models.DateField(auto_now_add=True)),
                ('adoptante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.adoptante')),
            ],
        ),
        migrations.CreateModel(
            name='MascotaAdoptada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observaciones_post_adopcion', models.TextField(blank=True)),
                ('mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.mascota')),
                ('adopcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.registroadopcion')),
            ],
        ),
        migrations.DeleteModel(
            name='Dog',
        ),
        migrations.DeleteModel(
            name='Adopter',
        ),
        migrations.DeleteModel(
            name='Preferences',
        ),
    ]
