# Generated by Django 5.2.3 on 2025-06-25 14:51

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_adoptante_gusta_raza_alter_mascota_raza'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adopcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Perro',
            fields=[
                ('identificador', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('tipo_raza', models.CharField(choices=[('CNH', 'Caniche'), ('CHH', 'Chihuahua'), ('LBD', 'Labrador'), ('PTB', 'Pitbull'), ('MTS', 'Mestizo')], max_length=4)),
                ('edad_aproximada', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(25)])),
                ('categoria_tamanio', models.CharField(choices=[('XS', 'Extra chico'), ('SM', 'Chico'), ('MD', 'Mediano'), ('LG', 'Grande'), ('XL', 'Muy grande')], max_length=3)),
                ('peso_actual', models.DecimalField(decimal_places=2, max_digits=5)),
                ('salud', models.CharField(choices=[('SAL', 'Salud estable'), ('OPR', 'Operado'), ('TRT', 'Bajo tratamiento')], max_length=3)),
                ('vacunado', models.BooleanField(default=False)),
                ('estado', models.CharField(choices=[('DISP', 'Disponible'), ('RESV', 'Reservado'), ('ADPT', 'Adoptado')], default='DISP', max_length=5)),
                ('comportamiento', models.CharField(choices=[('CLM', 'Calmo'), ('ACTV', 'Activo'), ('JGT', 'Juguetón'), ('PRTC', 'Protector')], max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='PersonaInteresada',
            fields=[
                ('documento', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('busca_raza', models.CharField(blank=True, choices=[('CNH', 'Caniche'), ('CHH', 'Chihuahua'), ('LBD', 'Labrador'), ('PTB', 'Pitbull'), ('MTS', 'Mestizo')], max_length=4, null=True)),
                ('busca_tamanio', models.CharField(blank=True, choices=[('XS', 'Extra chico'), ('SM', 'Chico'), ('MD', 'Mediano'), ('LG', 'Grande'), ('XL', 'Muy grande')], max_length=3, null=True)),
                ('busca_caracter', models.CharField(blank=True, choices=[('CLM', 'Calmo'), ('ACTV', 'Activo'), ('JGT', 'Juguetón'), ('PRTC', 'Protector')], max_length=4, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='registroadopcion',
            name='adoptante',
        ),
        migrations.RemoveField(
            model_name='mascotaadoptada',
            name='mascota',
        ),
        migrations.RemoveField(
            model_name='mascotaadoptada',
            name='adopcion',
        ),
        migrations.CreateModel(
            name='DetalleAdopcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seguimiento_post_adopcion', models.TextField(blank=True, null=True, verbose_name='Seguimiento')),
                ('adopcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='app.adopcion')),
                ('perro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adopciones', to='app.perro')),
            ],
        ),
        migrations.AddField(
            model_name='adopcion',
            name='interesado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.personainteresada'),
        ),
        migrations.DeleteModel(
            name='Adoptante',
        ),
        migrations.DeleteModel(
            name='Mascota',
        ),
        migrations.DeleteModel(
            name='MascotaAdoptada',
        ),
        migrations.DeleteModel(
            name='RegistroAdopcion',
        ),
    ]
